import week_1 from './tests/week-1.json'
import week_2 from './tests/week-2.json'
import week_3 from './tests/week-3.json'
import week_4 from './tests/week-4.json'
import week_5 from './tests/week-5.json'
import week_6 from './tests/week-6.json'
import week_7 from './tests/week-7.json'
import week_8 from './tests/week-8.json'
import week_9 from './tests/week-9.json'
import week_10 from './tests/week-10.json'
import week_11 from './tests/week-11.json'
import week_12 from './tests/week-12.json'
import week_13 from './tests/week-13.json'
import week_14 from './tests/week-14.json'
import week_15 from './tests/week-15.json'
import week_16 from './tests/week-16.json'
import week_17 from './tests/week-17.json'
import week_18 from './tests/week-18.json'
import week_19 from './tests/week-19.json'
import week_20 from './tests/week-20.json'
import week_21 from './tests/week-21.json'
import week_22 from './tests/week-22.json'
import week_23 from './tests/week-23.json'
import week_24 from './tests/week-24.json'
import week_25 from './tests/week-25.json'
import week_26 from './tests/week-26.json'
import week_27 from './tests/week-27.json'
import week_28 from './tests/week-28.json'
import week_29 from './tests/week-29.json'
import week_30 from './tests/week-30.json'

 
const arr = [week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18,week_19,week_20,week_21,week_22,week_23,week_24,week_25,week_26,week_27,week_28,week_29,week_30]
export default arr